### ISSUE TITLE
Unclear

### ISSUE THREAD

**Issue by rClicker** [WesternGamer/SlowMoOnDemand#2]
Hello! I appreciate your effort at creating this mod. I have bought the game off steam, i DO know where the root folder is, but in the .ini for this mod i can't figure out how to add a keybind? Not particularly a bug but I'd really like to know. Thanks!

**Comment by WesternSpace** [comment]
There is a section where you set the keybind. Here is the list of keycodes for that: https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
