### ISSUE TITLE
Is not working

### ISSUE THREAD

**Issue by yuriboeira11tx** [WesternGamer/SlowMoOnDemand#3]
I pressed the "Y" key a lot and nothing happens. My game is up to date and created the .ini file correctly, but it didn't work

**Comment by WesternSpace** [comment]
Do you have version.dll or dinput8.dll in your game directory? 

Do you also have ScriptHookRDR2.dll? 

Is there a file called SlowMoOnDemand.asi?

**Comment by yuriboeira11tx** [comment]
Yes, look:
![image](https://user-images.githubusercontent.com/26651347/203098399-7926810e-aa60-4696-beda-b7b73b5eee5b.png)

**Comment by yuriboeira11tx** [comment]
Downloaded archive "SlowMoOnDemand.asi" in: https://www.nexusmods.com/reddeadredemption2/mods/1621?tab=files&file_id=6429

**Comment by WesternSpace** [comment]
Delete the SlowMoOnDemand.ini file. The mod should regenerate the file. Then try pressing Y again ingame.

**Comment by yuriboeira11tx** [comment]
I did as recommended, but nothing happens when I press the "Y" key, does it have to do with my keyboard not having a numpad?

**Comment by yuriboeira11tx** [comment]
With other MODs the triggers for menus, etc... are working perfectly.

**Comment by WesternSpace** [comment]
Did the mod generate a config file? If it did, then another mod is setting the speed of the game to 1. Remove a asi mod at a time and restart the game until the mod works. There are no compatibility issues with Rampage.

**Comment by yuriboeira11tx** [comment]
Yes it is generating the ".ini" with the definition of variables and key trigger. Alright, I'll remove them to test

**Comment by yuriboeira11tx** [comment]
Confirmed, some other mod is interfering with this behavior. Thank you for your help!

**Comment by WesternSpace** [comment]
Glad to see that helped. What is the name of that other mod? I may make my mod patch that mod to make it compatible.

**Comment by yuriboeira11tx** [comment]
I found exactly the problem. In this trainer mod, there is an option unchecked by default in changing weathers, gameplay speed, etc... So just enable the option and both mods work!: https://www.nexusmods.com/reddeadredemption2/mods/190

**Comment by WesternSpace** [comment]
Glad to see that the problem has been fixed. Closing this issue as fixed.
